# See [Connector Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference)
# for more information about how to configure these tests

acceptance_tests:
  spec:
    tests:
      - spec_path: "source_excel_sheets/spec.py"
  
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
  
  discovery:
    tests:
      - config_path: "secrets/config.json"
        backward_compatibility_tests_config:
          disable_for_version: 0.0.0
  
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        expect_records:
          path: "integration_tests/expected_records.jsonl"
          exact_order: false
        
connector_image: airbyte/source-excel-sheets:dev
test_strictness_level: low